### ISSUE TITLE
Comments in HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [rodbinwa/prj-rev-bwfs-dasmoto#1]
Subtlety for errors!  Make sure your HTML document isn't commented out by making sure your comments use correct syntax. Line 1 has an opening comment tag with incorect syntax and doesn't have closing comment tag with correct syntax.  Instead your comments should follow this syntax:
`<!-- comment here -->`
where `<!--` is the opeing of the comment and `-->` is the close of the comment.

https://github.com/rodbinwa/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Index.html#L1-L2

**Comment by rodbinwa** [comment]
Fixed
