### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [rodbinwa/prj-rev-bwfs-dasmoto#3]
Simplify! Consider using locally stored images in your project as this is best practice for production code and will make your page load faster.  To do this you would create a new `images` folder inside your `Resources` folder, like this:
![screen shot 2017-09-01 at 12 02 37 pm](https://user-images.githubusercontent.com/11949479/30188214-2d0bf2e8-93e2-11e7-9602-7bd640df7a5e.png)

then save your images to this new folder, and use your `<img>` tags like this:
`<img src="./Resources/images/hacksaw.jpeg" alt="image of hacksaw paint brushes">`
Also, be sure to use descriptive `alt` attributes on your `<img>` elements (see above for example).  This helps with accessiblity and is best practice as well.

Example: https://github.com/rodbinwa/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Index.html#L17

**Comment by rodbinwa** [comment]
Put images in repo and linked locally.  Also added alt to each img.
