### ISSUE TITLE
Clean CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [rodbinwa/prj-rev-bwfs-dasmoto#4]
Great! Nice work with your CSS! It's very concise, orgainized, and easy to read.  Here I would consider using a group selector for the `font-weight: bold;` property. For example you could use:
```
.header h1, .products h2, .pricing {
  font-weight: bold;
}
```
Then delete all other instances of `font-weight: bold;` on those selectors.

**Comment by rodbinwa** [comment]
Updated the CSS as recommended.
